
global:
  scrape_interval:     15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: 
        - prometheus:9090
        
  - job_name: chip-shop
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
        - chip-shop:8080